### ISSUE TITLE
Track DLNA music playback

### ISSUE THREAD

**Issue by ghostfreeman** [jesseward/plex-lastfm-scrobbler#39]
I don't know if Plex logs these, but I am not seeing any reported media playback when using the DLNA protocol. Would be a nice feature.

**Comment by jesseward** [comment]
hi @ghostfreeman . AFIAK DLNA is not logged in the PMS log file. The logic of this utility requires the song to be logged with an ID of the item from the Plex library. The script then makes a call to the Plex API in order to fetch metadata about that track.

For the DNLA specific use case unfortunately plex-lastfm-scrobbler will *not* work.
